### ISSUE TITLE
[1993J] need to digitize

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/sne-external-spectra#14]
sne-external-spectra/Suspect/II_spec_ascii_20110715/1993J/1993J_19930528_3226_9359_00.dat

This spectrum (at MJD 49135) has the appearance of being de-redshifted too many times--but something else is odd about its wavelength solution. It will need to be either digitized or requested from the original source since there is not a fix on WISeREP.

Will remove on the next PR, but I will leave this issue up-- @guillochon could you add a "help wanted" label for this one? I do not appear to be able to.

**Comment by guillochon** [comment]
@jparrent Was this addressed in https://github.com/astrocatalogs/sne-external-spectra/pull/54? If so please close this issue at your convenience.
