### ISSUE TITLE
CfA Ibc, SUSPECT, and UCB spectra have unknown flux unit

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/sne-external-spectra#2]
@jparrent The CfA Ibc folder has strange units for the fluxes, they are order unity instead of ~1e-17 like the Ia fluxes. The readme doesn't indicate what the proper normalization is. We should update the readme so that the fluxes can be properly imported.

**Comment by guillochon** [comment]
@jparrent I just noticed that the SUSPECT and UCB folders have the same issue. Could you add README files to each of those directories, just with basic unit information?

**Comment by jparrent** [comment]
@guillochon Units are reported as "erg/s/cm^2/A" but the scaling suggests "arbitrary units" -- looking into this.

**Comment by jparrent** [comment]
@guillochon Okay I see. README with CfA_SNIbc data release indicates the spectra have not been scaled to match the photometry, hence no 10^-17. I suspect the same for UCB and some from SuSpect. Long-term, the photometry could be used to approximate the scale of the spectra.

**Comment by guillochon** [comment]
Do you think the papers would have this info?
