### ISSUE TITLE
[CSP] redshift corrections

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/sne-external-spectra#25]
sne-external-spectra/CSP/

All CSP spectra released have already been corrected for redshift, and so they appear twice corrected in the Open Supernova Catalog. Should remove the correction in the script for the CSP data. 

Once done, we one need to go one by one for CSP data.

**Comment by guillochon** [comment]
@jparrent, they appear twice? I'm not sure that's related to the de-redshifting, that's a tag applied to each spectrum when it's added. I'm guessing another of the sources we are pulling from happens to contain CSP data. Could you link an example event with duplicate spectra?

**Comment by jparrent** [comment]
@guillochon The CSP data have been corrected for redshift twice, once in the CSP data release, and once by us. So, the CSP data shouldn't be corrected again in the script. Pardon the confusion.

**Comment by guillochon** [comment]
@jparrent Ah OK, this is actually not CSP-specific, it's for any spectrum I've marked "deredshifted," the spectra plotting routine presumed everything was rest-frame. I've fixed this now and the spectra should be plotted properly so long as the "deredshifted" flag is attached to the spectra that have already been deredshifted.

**Comment by jparrent** [comment]
@guillochon Got it. I will be combing through the catalog a number of times, so I'll report back on anything related to this.

**Comment by jparrent** [comment]
CSP looks good for redshift corrections. Closing this issue.
