### ISSUE TITLE
[2005cs] delete one spectrum

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/sne-external-spectra#34]
sne-external-spectra/Suspect/II_spec_ascii_20110715/2005cs/2005cs_20050719_3311_7202_00.dat

This spectrum appears to have been corrected for redshift more than 10 times, and the data are so noisy that it cannot be properly reset to the observer frame through the help of telluric features. 

I recommend removing it. Currently there is enough data for SN 2005cs that it is not critical to leave the spectrum up as is. It could also be placed in a ``to_be_digitized" folder that I could get to later.

**Comment by jparrent** [comment]
Deleted from my fork. Will be fixed upon the next pull request, after which I will close this issue.

**Comment by guillochon** [comment]
@jparrent Many of these should be addressed with the recently merged PR, could you check that they have been fixed? Thanks!

**Comment by jparrent** [comment]
@guillochon All but the redshift corrections and trimming issues were closed. I take it we'll have to wait for the spectra to be sucked up again for those? I will continue to monitor.

**Comment by guillochon** [comment]
They should be all incorporated, whatever was in the PR at least. I'll
check the open issues.

On Saturday, February 20, 2016, J. Parrent <notifications@github.com> wrote:

> @guillochon <https://github.com/guillochon> All but the redshift
> corrections and trimming issues were closed. I take it we'll have to wait
> for the spectra to be sucked up again for those? I will continue to
> monitor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astrocatalogs/sne-external-spectra/issues/34#issuecomment-186664712>
> .
>


-- 
James Guillochon
Einstein Fellow at the Harvard-Smithsonian CfA
jguillochon@cfa.harvard.edu

**Comment by jparrent** [comment]
I'll double check in a few hours so no hurry. I'll respond to the specific
issues if I find no changes. Some of them may just be related to the
separate issues of CSP and BSNIP redshift corrections, which I have not
made changes to (script specific).
