### ISSUE TITLE
[BSNIP] redshift corrections

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/sne-external-spectra#49]
sne-external-spectra/BSNIP

I have yet to check all supernova spectra from the BSNIP release, but so far the following events do not appear to have been corrected for redshift by the scripts. 

05M
01V
05el
04dt
06D
99dq
05hc
05am
04ef

**Comment by jparrent** [comment]
@guillochon This issue does not appear to be resolved; i.e. when I find spectra that are off, or have the appearance of being corrected twice for redshift, the data are from the UCB/BSNIP set. Is there still a place in one of the scripts where these spectra are being corrected twice?

**Comment by guillochon** [comment]
@jparrent Your eye is probably better trained than mine but I couldn't see anything obvious in SN2005M. Could you give me a specific spectrum that appears to be off? An event name + days to max should be enough to help me track it down.

**Comment by jparrent** [comment]
@guillochon Ah but apparently not good enough. Two things may be happening though. The spectra in question, e.g 06X at +46.7, 67.57, 74.53, are sourced to SUSPECT and UC SNDB. If the data are in fact from SUSPECT, then the UCB issue can be closed and I will just continue correcting spectra (without renaming them) when I get back from break. Can you confirm the source for those listed above?

**Comment by jparrent** [comment]
@guillochon The more I think about it, it only makes sense that it would be data from SuSpect. I will pick up where I left off with redshift corrections. I do recall having to wait for CSP and BSNIP issues to be fixed (which I now agree, they are) before continuing the correction process for SuSpect. Thanks for the oversight, tffn.

**Comment by jparrent** [comment]
This is fixed. Closing.
