### ISSUE TITLE
[2005cf] redshift corrections

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/sne-external-spectra#53]
@guillochon For some reason, the 2005cf spectra from Wang et al. 2009 (reference #13; http://adsabs.harvard.edu/abs/2009ApJ...697..380W) are not being corrected for redshift. I have triple-checked that the source files are accurate (they are), but the spectra remain uncorrected in the plots. 

This screen shot shows what's going on here for one of them. The one in the middle is the one that's off. It should be shifted toward the blue (left) is all.
![wang_05cf_spectrum](https://cloud.githubusercontent.com/assets/7276612/13135048/e48fb0e8-d5da-11e5-84ca-422673fb6cdb.png)

The others (middle spectrum):
![screen shot 2016-02-18 at 1 03 11 am](https://cloud.githubusercontent.com/assets/7276612/13135098/7b2860f4-d5db-11e5-8427-5a5ec6298307.png)
![screen shot 2016-02-18 at 1 03 28 am](https://cloud.githubusercontent.com/assets/7276612/13135099/7e5b6bc2-d5db-11e5-94f4-3921ec7a623d.png)

.

**Comment by guillochon** [comment]
@jparrent I've removed the "deredshifted" flag from all the SNDB entries. Could you check that these are now correct?

**Comment by jparrent** [comment]
This is fixed. Closing issue.
