### ISSUE TITLE
sources.json for SUSPECT needs updates

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/sne-external-spectra#57]
@jparrent I just noticed that since we are associating SUSPECT reference info with a filename, where the filename comes from the original SUSPECT webpage, the spectra for which the filename has been changed (when we're say de-redshifting spectra) are not being properly associated with their sources. So currently a number of the spectra being pulled from SUSPECT are source-less in the catalog.

To correct this, there's a [sources.json](https://github.com/astrocatalogs/sne-external-spectra/blob/master/Suspect/sources.json) file that was generated by the download-suspect.py script from the SUSPECT website, that .json file needs to be manually edited to account for the file name changes.

Two other things I noticed in this file: ~~Some of the bibcodes are ArXiv bibcodes and have been published since then, these should be changed to the published bibcodes.~~ Secondly, there are at least a few dozen spectra for which the SUSPECT page contains no source info at all (the keys have a blank bibcode value in sources.json); if we can figure out where these files came from we should add those bibcodes to the sources.json file as well.

**Comment by guillochon** [comment]
I was able to replace the ArXiv bibcodes pretty quickly, so that part is done. It's the filename changes and the filenames with no source that are trickier.

**Comment by jparrent** [comment]
@guillochon MM I see. I will work on this, thanks for the list!

**Comment by jparrent** [comment]
@guillochon This issue can be closed after the PR for source.json.

**Comment by guillochon** [comment]
@jparrent So the PR addresses the missing sources issue (thanks!), but the filenames issue is still present (many of the spectra files were renamed after deredshifting). I know not all of the files you renamed were in SUSPECT though, it was just a bit hard to track down the list for SUSPECT by looking at the commit history.

**Comment by jparrent** [comment]
@guillochon I see. After I am back next Monday, and pending your recommendations, I could look to revert those changes filenames to the original.

**Comment by jparrent** [comment]
@guillochon I could also do this today. Let me know and I can get on it.

**Comment by jparrent** [comment]
@guillochon It also might be best to merge with my sne-external-spectra, as there are some updates, and then I can go find and fix the renamed files.

**Comment by guillochon** [comment]
@jparrent Testing the current PR now, prolly best to do a separate PR for the name changes.

**Comment by jparrent** [comment]
@guillochon Agreed. Standing down until then.

**Comment by guillochon** [comment]
Closing this as I think we've resolved it.
